### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by JohanLeirnes** [diogos88/HA-H801-ESP8266-MQTTJson-RGB#1]
Hello

The transition does not seem to happen when turning off the light. Nor when turning on the lights, seems that this should follow DEFAULT_TRANSITION_STEPS.

Also a tip to get this smooth is to always reset brightness to 0 when turning off the lamp. 
This way this scenario will never happen:

Yesterday you had the lamp on at 255 brightness
Today when you wake up you have a automation that will turn on the lamp at 15 brightness when you wake up.

Right now what will happen is that the lamp will turn on to 255 and then transition to 15. That would kind of be bad.

I tried to implement that the brightness is always set to 0 and state is set to LIGHT_OFF when LIGHT_OFF is recieved but im not good enough at programming to get this to work.

**Comment by JohanLeirnes** [comment]
Im also guessing that the first issue is because brightness is not set to 0 when turning off. so that way then turning off it goes to just turn off 255 brightness. aka no trans. and when turning on it goes from off to on and 255 -> 255 aka no trans again.

**Comment by JohanLeirnes** [comment]
I made it work temporarly by modding the mqtt_json.py file to send this on turn_on

        if ATTR_BRIGHTNESS not in kwargs:
            message = {"state":"ON","brightness":255}
        else:
            message = {'state': "ON"}

and this on turn_off 

        message {"brightness":0}

**Comment by diogos88** [comment]
Sorry for the big delay. I never saw this issue...

I modified the code to set the brightness to 0 when the state is changed to OFF.
